let os=require('os')
//console.log(os.arch())
//console.log(os.hostname())
//console.log(os.platform())
//console.log(os.tmpdir())
//console.log(os.type())
//console.log(os.userInfo())
console.log(os.freemem())
console.log(os.totalmem())
console.log(os.homedir())
